// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAly7tGM71x0Uo8yEWTG4hOhAenfvx9gKU',
    appId: '1:464097960550:android:5d130b5ee684f7f29fc3a7',
    messagingSenderId: '464097960550',
    projectId: 'smartfit-c0530',
    storageBucket: 'smartfit-c0530.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBu70uJLpPYHVUx-K-TjSwdt5GKfJY-l4',
    appId: '1:464097960550:ios:30828f3608fa61fb9fc3a7',
    messagingSenderId: '464097960550',
    projectId: 'smartfit-c0530',
    storageBucket: 'smartfit-c0530.firebasestorage.app',
    iosBundleId: 'com.example.applicationMain',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAly7tGM71x0Uo8yEWTG4hOhAenfvx9gKU',
    appId: '1:464097960550:web:5d130b5ee684f7f29fc3a7',
    messagingSenderId: '464097960550',
    projectId: 'smartfit-c0530',
    authDomain: 'smartfit-c0530.firebaseapp.com',
    storageBucket: 'smartfit-c0530.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );
}
